name: Deploy to Commons

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build --dev
      - env:
          SSH_KEY: ${{ secrets.TOOLFORGE_KEY }}
          USERNAME: ${{ secrets.WIKI_USERNAME }}
          PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/id_rsa
          chmod og-rwx ~/.ssh/id_rsa

          # Create a tunnel in the background, delete the key,
          # and set a TRAP to kill the tunnel on exit
          ssh -N -L 8443:localhost:443 ${{ secrets.TOOLFORGE_USER }}@tools-login.wmflabs.org &
          rm ~/.ssh/id_rsa
          trap "kill $!" EXIT

          # run user's own script to login and publish build results to pages
          npm run deploy --dev --noi18n
